#! /bin/sh

current=$(task next 2> /dev/null)

if [[ -z $current ]]; then
  notify-send "Task Warrior" "Found pending tasks."
  exit 1
else
  task list | 
    awk '(NR > 3) && (NF > 2) {print}' |
    dmenu -p "Task: " -l 10 |
    awk '{print $1}' |
    task $(</dev/stdin) delete
fi
