#! /bin/bash

current=$(task next 2> /dev/null)

if [[ -z $current ]]; then
  notify-send "Task Warrior" "No tasks to take notes on."
  exit 1
else
  task list | 
    awk '(NR > 3) && (NF > 2) {print}' |
    dmenu -p "Task: " -l 10 |
    awk '{print $1}' |
    $BSPS/task/edit_note
fi
