#!/bin/sh

## Directory of the running script
## for when I shuffle files around on relative paths
basedir=$(dirname "$0")

# TODO need to check if password will work,
#   before attempting to install
get_sudo_permission() {
    echo "I need sudo permissions for some operations"

    echo -n "  Password: "
    read -s password
}

download_git_repos() {
    mkdir $HOME/packages
    git clone https://aur.archlinux.org/yay.git $HOME/packages/yay
    git clone https://github.com/ccod/st.git $HOME/packages/st
    git clone https://github.com/ccod/dmenu.git $HOME/packages/dmenu
    git clone https://github.com/adi1090x/slim_themes.git $HOME/packages/slim_themes
}

install_pacman_packages() {
    list=$(< ./pkglist.txt)
    echo $password | sudo -S pacman -S --noconfirm $list
}

install_dmenu_st_packages() {
    cd $HOME/packages/dmenu
    make
    echo $password | sudo -S make install

    cd $HOME/packages/st
    make
    echo $password | sudo -S make install
}

# figure out sed to replace default theme with mine
install_slim_themes() {
    echo $password | sudo -S cp -R $HOME/packages/slim_themes/themes/* /usr/share/slim/themes/
    # make change to /etc/slim.conf
}

# in case files already exist in there from package installation
install_config() {
    /usr/bin/rsync -a $basedir/../.config $HOME
    /usr/bin/rsync -a $basedir/../.local $HOME
    cp $basedir/../.xinitrc $HOME/
    echo $password | sudo -S cp $basedir/../zshenv /etc/zsh/

    # I use ohmyzsh, this sets the install env
    export ZSH="$HOME/.config/zsh/.oh-my-zsh"
    sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
}

enable_systemd_services() {
    echo $password | sudo -S systemctl enable slim
    echo $password | sudo -S systemctl enable NetworkManager
    echo $password | sudo -S systemctl enable systemd-timesyncd
    echo $password | sudo -S systemctl enable docker
}


# Does all the work
get_sudo_permission

download_git_repos
install_pacman_packages
install_dmenu_st_packages
install_slim_themes
enable_systemd_services
install_config

echo -e "\n\n==============================="
echo -e "== Finished Main Install"
echo -e "==============================="
echo -e "\nScripts that require a bit more babysitting:"
echo -e "\t./aur-install\n\t./emacs-config-install\n"
