#! /bin/sh

bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc desktop -f 1

bspc config border_width 1
bspc config window_gap 0

bspc config normal_border_color "#1d1d1d"
bspc config focused_border_color "#333333"

bspc rule -a Emacs state=tiled
bspc rule -a bigboy state=floating
